source :rubygems
gem 'sinatra', '1.3.3'
gem 'sqlite3-ruby', '~> 1.3.1'
gem 'rsolr'
gem 'facets'
gem 'activerecord', '~>3.2'

gem 'sunspot', :path => File.expand_path('../../sunspot', __FILE__)
gem 'sunspot_solr', :path => File.expand_path('../../sunspot_solr', __FILE__)
gem 'sunspot_sinatra', :path => File.expand_path('..', __FILE__)

group :test do
	gem 'rake', '0.9.2.2'
	gem 'rack-test'
	gem 'rspec', '~> 2.11'
	gem 'ruby-debug19', :require => nil,  :platforms => :mri_19
	gem 'test-unit', '1.2.3',             :platforms => :mri_19
end
